stages:
  data:
    cmd: python get_data.py
    outs:
      - data/train_features.csv
      - data/test_features.csv
      - data/train_labels.csv
      - data/test_labels.csv

  train:
    cmd: >-
      python train.py
      --epochs ${epochs}
      --starting_epoch ${starting_epoch}
      --batch_size ${batch_size}
    params:
      - epochs
      - starting_epoch
      - batch_size
    deps:
      - data/train_features.csv
      - data/test_features.csv
      - data/train_labels.csv
      - data/test_labels.csv
    outs:
      - model.pt
    metrics:
      - metrics.json:
          cache: false